language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - pip install --user codecov
after_success:
  - codecov
before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
  - bash scripts/create-hash-sum.sh target/dungeon-${TRAVIS_TAG}.jar
deploy:
  provider: releases
  api_key:
    secure: SS+0XrFZBqJRAKvghsaZ3op1/UzKvip3osFoSX2oS1EOpRQnCyJmH0oJlIJsAQfnz8jZ4DDqUCEHK1UyJJjaZpEv2KKrTslYw3D6chOHmWlQnHvUF60KcmYRg/Qs0dTSep4fDcElh8vTqh03VjcxH41Dt0+qjKHhFKzjMDM0RT7OUYvvZI00aZOWAdfgoVmcTZauZRggLgwj5DGw4VaFqHg9m3MASj4J/yQao5c9K/tvwd8rm3V/Dvq/kJtNJ5eYKlNz/0bkCXiNFzXTz1cVoymLFpZcckBgxO0TUmgejwFNknAAqPYeCLVMJ6gh3oDbYr8JYLwimL/q5nMPZo4C2vFRUzOOHACwsTSKDOgclcP3nYAOLmUtP6Tl8/iXoMo4E1gDNGkOSELB/o2kL+Ptu1ck6bR7tvIxHgttQor/zibVoTQbafJBNowtYD6aBokZ3ZSa6YUiSKLUB26TRZ/vhzNNGnym/oTQu74q1cE7ThN5Ht20pOG9ujj5xPst0d/om19mi/oB/7HpI5I8/8Y4Z9G0Mk/BUPUQ6eu4g6vOG7sa7xuiD60Xle+ZjAOL0r9Njl8iNmHfv2QLlxGRjlDenVJZGCY6NhrT8XmKqZVRi7/QxAzQ8ZQjnP8cA9wqtkmTMxZFfY3LsY8jW46y7EWAFLw5azvlKocgpM1/pNqyZkg=
  file:
    - target/dungeon-${TRAVIS_TAG}.jar
    - target/dungeon-${TRAVIS_TAG}.jar.sha256
  skip_cleanup: true
  on:
    tags: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HmxadjZ+WagbCKezkiiz8b86mwsV19jfdY5QgG123mHa9ueyTn+4smGjEtjn6Ypz0pJqXpaTwEL3hXvHu7F4H57/03RlOajolhNyulg2bA/xRvSxr7Al3Kpsi3fUfInNo+OVtM54/nsHc+xPsKLorpkAWW5O6LJkQmj6gfaJuxp0fgi1dcD9f/NfKOjbBpbTASZOQb+DosfI+HG2tKc6zI86IBf/SpdBhOyxwXrX33YzrrKdZd6QIF+e2U69QygqIpsL0nBm2fT51hOH2FTq/txPXCNH8oGGLP9E2BVwoB6IENlQgrBQeiQHtq3olBr9RsiEZ2mI4J0vQXuYXKn2iDc4by9t92DRK4fkxqbfatNYG9X1btYgAg5WvGIFW/Xm+XJuRJH0TCzzd5BaoeGQemhkYJnN6PCvxSUv4ecWrem2XqAESaVUO1FeJZ/bHC5feZL3VCFuB2GTXPZ8wdDMCtrlqG/Jusp8694EzQwGMWRxAIPg43LHV3wB7kD7gIreH9OC86H4USROXv9c2QnRykT1JHqC0N8dgzOEAzJdm59+0jE/CwdVgCjqF2AhNgjnm3RXV1x30ZqHQNNIwWvtqlCLbtYQ+Pp1q+brrGVZ0HwVs9DJhoDT9MU13JnpJCRPlpcxFc82+TcXSVKe6m7OpEq7cErWLgw5basYPUzXljA="

addons:
  coverity_scan:
    project:
      name: "mafagafogigante/dungeon"
      description: "Build submitted via Travis CI."
    notification_email: mafagafogigante@gmail.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
